### ISSUE TITLE
[Breaking Bug] Getting HTTP 503 – Service Unavailable when posting review/question as guest (not logged in)

### ISSUE THREAD

**Issue by 23d1** [owldesign/QARR#21]
I'm back at testing and evaluating right now, and there seems to be an issue where the submitting a post throws a 503 - Service Unavailable error when the posting user is not a logged in user (guest, essentially).

Here's the stack trace;
```
craft\web\ServiceUnavailableHttpException in /Users/a/Sites/test/craft/vendor/craftcms/cms/src/web/Controller.php:163
Stack trace:
#0 /Users/a/Sites/test/craft/vendor/yiisoft/yii2/base/Controller.php(155): craft\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /Users/a/Sites/test/craft/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('save', Array)
#2 /Users/a/Sites/test/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save', Array)
#3 /Users/a/Sites/test/craft/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('qarr/reviews/sa...', Array)
#4 /Users/a/Sites/test/craft/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('qarr/reviews/sa...', Array)
#5 /Users/a/Sites/test/craft/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#6 /Users/a/Sites/test/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#7 /Users/a/Sites/test/web/index.php(21): yii\base\Application->run()
```

**Comment by owldesign** [comment]
@23d1  please pull latest version 1.1.9. Let me know if you still having issues.

Thanks.

**Comment by 23d1** [comment]
Killer! Thanks.
