### ISSUE TITLE
500 Error When Posting Question (v1.2.0)

### ISSUE THREAD

**Issue by 23d1** [owldesign/QARR#23]
For some reason, after the 1.2.0 update, I get a 500 error when posting a question. Gonna dig a bit, to make sure it's not my xmlhttprequest going crazy.

**Comment by 23d1** [comment]
Here's the stack trace for the 500 error;

```
Exception: Serialization of 'Closure' is not allowed in /Users/a/Sites/a/craft/vendor/yiisoft/yii2-queue/src/serializers/PhpSerializer.php:24
Stack trace:
#0 /Users/a/Sites/a/craft/vendor/yiisoft/yii2-queue/src/serializers/PhpSerializer.php(24): serialize(Object(owldesign\qarr\jobs\RulesTask))
#1 /Users/a/Sites/a/craft/vendor/yiisoft/yii2-queue/src/Queue.php(161): yii\queue\serializers\PhpSerializer->serialize(Object(owldesign\qarr\jobs\RulesTask))
#2 /Users/a/Sites/a/craft/vendor/craftcms/cms/src/queue/Queue.php(148): yii\queue\Queue->push(Object(owldesign\qarr\jobs\RulesTask))
#3 /Users/a/Sites/a/craft/vendor/owldesign/qarr/src/elements/Question.php(738): craft\queue\Queue->push(Object(owldesign\qarr\jobs\RulesTask))
#4 /Users/a/Sites/a/craft/vendor/craftcms/cms/src/services/Elements.php(1975): owldesign\qarr\elements\Question->afterSave(true)
#5 /Users/a/Sites/a/craft/vendor/craftcms/cms/src/services/Elements.php(488): craft\services\Elements->_saveElementInternal(Object(owldesign\qarr\elements\Question), true, false)
#6 /Users/a/Sites/a/craft/vendor/owldesign/qarr/src/controllers/QuestionsController.php(120): craft\services\Elements->saveElement(Object(owldesign\qarr\elements\Question))
#7 [internal function]: owldesign\qarr\controllers\QuestionsController->actionSave()
#8 /Users/a/Sites/a/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /Users/a/Sites/a/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /Users/a/Sites/a/craft/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('save', Array)
#11 /Users/a/Sites/a/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save', Array)
#12 /Users/a/Sites/a/craft/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('qarr/questions/...', Array)
#13 /Users/a/Sites/a/craft/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('qarr/questions/...', Array)
#14 /Users/a/Sites/a/craft/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#15 /Users/a/Sites/a/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /Users/a/Sites/a/web/index.php(21): yii\base\Application->run()
#17 /Users/a/.composer/vendor/laravel/valet/server.php(158): require('/Users/a/Sites/...')
#18 {main}
```

**Comment by owldesign** [comment]
Just saw this, will fix today.

**Comment by owldesign** [comment]
@23d1 pull latest, should have that fixed now!

**Comment by 23d1** [comment]
Awesome!
