### ISSUE TITLE
QARR breaks with Craft CMS 3.5

### ISSUE THREAD

**Issue by 23d1** [owldesign/QARR#30]
```
Error: Undefined class constant 'EVENT_AFTER_SAVE' in /Users/a/Site/craft/vendor/owldesign/qarr/src/QARR.php:108
Stack trace:
#0 /Users/a/Site/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): owldesign\qarr\QARR->init()
#1 /Users/a/Site/craft/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#2 /Users/a/Site/craft/vendor/craftcms/cms/src/base/Plugin.php(115): yii\base\Module->__construct('qarr', Object(craft\web\Application), Array)
#3 [internal function]: craft\base\Plugin->__construct('qarr', Object(craft\web\Application), Array)
#4 /Users/a/Site/craft/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#5 /Users/a/Site/craft/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('owldesign\\qarr\\...', Array, Array)
#6 /Users/a/Site/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('owldesign\\qarr\\...', Array, Array)
#7 /Users/a/Site/craft/vendor/craftcms/cms/src/services/Plugins.php(908): yii\BaseYii::createObject(Array, Array)
#8 /Users/a/Site/craft/vendor/craftcms/cms/src/services/Plugins.php(227): craft\services\Plugins->createPlugin('qarr', Array)
#9 /Users/a/Site/craft/vendor/craftcms/cms/src/base/ApplicationTrait.php(1403): craft\services\Plugins->loadPlugins()
#10 /Users/a/Site/craft/vendor/craftcms/cms/src/web/Application.php(104): craft\web\Application->_postInit()
#11 /Users/a/Site/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#12 /Users/a/Site/craft/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#13 /Users/a/Site/craft/vendor/craftcms/cms/src/web/Application.php(92): yii\base\Application->__construct(Array)
#14 [internal function]: craft\web\Application->__construct(Array)
#15 /Users/a/Site/craft/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#16 /Users/a/Site/craft/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#17 /Users/a/Site/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#18 /Users/a/Site/craft/vendor/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject(Array)
#19 /Users/a/Site/craft/vendor/craftcms/cms/bootstrap/web.php(51): require('/Users/a/Sites/...')
#20 /Users/a/Site/web/index.php(20): require('/Users/a/Sites/...')
#21 /Users/a/.composer/vendor/laravel/valet/server.php(191): require('/Users/a/Site/...')
#22 {main}
```

**Comment by owldesign** [comment]
Lates version 1.2.2.1 should fix this bug!

**Comment by edwardpmartinez** [comment]
Thank you @owldesign
